# **Understanding Numpy**

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import time

# Check Numpy version
print(f"Numpy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=4, suppress=True)

Numpy version: 2.3.2


In [5]:
## Creating Numpy Arrays
# 1D Array: A simple sequence of numbers
arr1d = np.array([1, 2, 3, 4, 5])

# 2D array: Think of this as a matrix or table with rows and columns
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# 3D array: Like a stack of 2D arrays - useful for images, time series, etc.
arr3d = np.array([[[1,2], [3,4], [5,6], [7,8]]])

print("1D array:", arr1d)
print("2D array:\n", arr2d)
print("3D array:\n", arr3d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [23]:
#  Creating Special Arrays in Numpy
# Creating arrays filled with zeros - useful for initializing arrays
# Shape (3, 4) means 3 rows and 4 columns
zeros = np.zeros((3, 4))

#  Creating arrays filled with ones - often used as starting points
ones = np.ones((2, 3, 4))           # 3D array: 2 layers, 3 rows, 4 columns

#  Empty array - faster than zeros/ones but contains random values
# Use when you'll immediately fill the array with real data 
empty = np.empty((2, 2))

print("Zeros array (3x4):\n", zeros)
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n", empty)

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[0. 0.]
 [0. 0.]]


In [27]:
#  Range arrays - like Python's range() but more powerful
range_arr = np.arange(0, 10, 2)        # Start, stop, step: [0, 2, 4, 6, 8]
print("Range array:", range_arr)

# Linearly spaced arrays - divide a range into equal parts
# From 0 to 1 with exactly 5 points (including endpoints)
linspace_arr = np.linspace(0, 1, 5)  
print("Linspace array:", linspace_arr)

# Logarithmically spaced arrays - useful for scientific data
# From 10^0 to 10^2 (1 to 100) with 5 points
logspace_arr = np.logspace(0, 2, 5)  
print("Logspace array:", logspace_arr)

Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Logspace array: [  1.       3.1623  10.      31.6228 100.    ]


In [ ]:
# Identity matrix - diagonal of ones, zeros elsewhere
# Essential for linear algebra operations
identity = np.eye(4)              # 4x4 identity matrix

# Diagonal matrix - put values on the diagonal
diagonal = np.diag([1, 2, 3, 4])  

# Array filled with a specific value
full_arr = np.full((3, 3), 7)     # 3x3 array filled with 7

print("Identity matrix:\n", identity)
print("Diagonal matrix:\n", diagonal)
print("Full array (filled with 7):\n", full_arr)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[2 2 2]
 [2 2 2]
 [2 2 2]]


## Numpy data Types (dtypes)
- Understanding data types is crucial for memory efficiency and numerical precision.

In [38]:
# Explicit data types - control memory usage and precision
int_arr = np.array([1, 2, 3], dtype=np.int32)       # 32-bit integers
float_arr = np.array([1, 2, 3], dtype=np.float64)   # 64-bit floats (double precision)
bool_arr = np.array([True, False, True], dtype=np.bool_)  # Boolean values

# Type conversion - change dtype of existing array
converted = int_arr.astype(np.float32)  # Convert to 32-bit float

print("Integer array dtype:", int_arr.dtype)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)
print("Converted array dtype:", converted.dtype)

# Memory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

Integer array dtype: int32
Float array dtype: float64
Boolean array dtype: bool
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 8 bytes per element
